<a href="https://colab.research.google.com/github/beyzadurdu6619/ML/blob/main/LinearRegression_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [39]:
df=pd.read_csv('student.csv')

In [40]:
df.head(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [41]:
df=pd.get_dummies(df,columns=['Extracurricular Activities'],drop_first=True)

In [44]:
df.columns=['saat','son_not','uyku_saati','pratik_sayisi','not','faaliyet']

In [45]:
df.head(3)

   saat  son_not  uyku_saati  pratik_sayisi   not  faaliyet
0     7       99           9              1  91.0      True
1     4       82           4              2  65.0     False
2     8       51           7              2  45.0      True

In [47]:
df['not']=df['not'].astype(int)
df.head(3)

   saat  son_not  uyku_saati  pratik_sayisi  not  faaliyet
0     7       99           9              1   91      True
1     4       82           4              2   65     False
2     8       51           7              2   45      True

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   saat           10000 non-null  int64
 1   son_not        10000 non-null  int64
 2   uyku_saati     10000 non-null  int64
 3   pratik_sayisi  10000 non-null  int64
 4   not            10000 non-null  int64
 5   faaliyet       10000 non-null  bool
dtypes: bool(1), int64(5)
memory usage: 400.5 KB

In [49]:
y=df['not']
x=df.drop('not',axis=1)

In [52]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
df.head(3)

   saat  son_not  uyku_saati  pratik_sayisi  not  faaliyet
0     7       99           9              1   91      True
1     4       82           4              2   65     False
2     8       51           7              2   45      True

In [58]:
l=LinearRegression()
model=l.fit(x_train,y_train)

In [57]:
model.predict([[10,60,8,3,1]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([60.6218279])

In [ ]:
#y=a1*x1+a2*x2+b

In [60]:
model.coef_ #katsayı a1,a2,a3...

array([2.85248393, 1.0169882 , 0.47694148, 0.19183144, 0.60861668])

In [62]:
model.intercept_ #sabit

np.float64(-33.921946215556396)

In [63]:
y_value=(model.coef_[0]*10)+(model.coef_[1]*60)+(model.coef_[2]*8)+(model.coef_[3]*3)+(model.intercept_)
print(y_value)

60.01321121890711

In [64]:
x1=model.score(x_test,y_test)

In [65]:
x2=model.score(x_train,y_train)

In [66]:
son=x1-x2
print(son)

0.0002934118890790538