<a href="https://colab.research.google.com/github/beyzadurdu6619/ML/blob/main/MobileBankClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [25]:
df=pd.read_csv("bankv3.csv")

In [26]:
df.head(3)

   Unnamed: 0                      sorgu      label  le
0           0    kredi kartımı kaybettim  kartkayip   1
1           1    banka kartımı kaybettim  kartkayip   1
2           2  kredi kartımı bulamıyorum  kartkayip   1

In [27]:
df=df[["sorgu","label"]]

In [28]:
df.head(3)

                       sorgu      label
0    kredi kartımı kaybettim  kartkayip
1    banka kartımı kaybettim  kartkayip
2  kredi kartımı bulamıyorum  kartkayip

In [29]:
stopwords=['fakat','lakin','ancak','acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']

In [30]:
for word in stopwords:
  word=" "+word+" "
  df["sorgu"]=df["sorgu"].str.replace(word," ")
df.head(3)

                       sorgu      label
0    kredi kartımı kaybettim  kartkayip
1    banka kartımı kaybettim  kartkayip
2  kredi kartımı bulamıyorum  kartkayip

In [31]:
cv=CountVectorizer(max_features=50)
x=cv.fit_transform(df["sorgu"]).toarray()
y=df["label"]

In [32]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.9714285714285714