In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
train_data=pd.read_csv("/kaggle/input/competitions/titanic/train.csv")
test_data=pd.read_csv("/kaggle/input/competitions/titanic/test.csv")
#com_data=pd.read_csv("/kaggle/input/competitions/titanic/gender_submission.csv")

In [3]:
# Her iki veri kümesini bir liste içinde döngüye alarak doldurma
for dataset in [train_data, test_data]:
    dataset['Cabin'] = dataset['Cabin'].ffill().bfill()

In [4]:
train_data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S

In [5]:
test_data.head(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B45,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B45,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B45,Q

In [6]:
train_data=train_data.drop(columns=["Name","Parch","Ticket","SibSp","Fare","Embarked","Cabin"],axis=1)

In [7]:
test_data=test_data.drop(columns=["Name","Parch","Ticket","SibSp","Fare","Embarked","Cabin"],axis=1)

In [8]:
train_data

     PassengerId  Survived  Pclass     Sex   Age
0              1         0       3    male  22.0
1              2         1       1  female  38.0
2              3         1       3  female  26.0
3              4         1       1  female  35.0
4              5         0       3    male  35.0
..           ...       ...     ...     ...   ...
886          887         0       2    male  27.0
887          888         1       1  female  19.0
888          889         0       3  female   NaN
889          890         1       1    male  26.0
890          891         0       3    male  32.0

[891 rows x 5 columns]

In [9]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
dtypes: float64(1), int64(3), object(1)
memory usage: 34.9+ KB

In [10]:
y=train_data["Survived"]
X = pd.get_dummies(train_data,columns=["Sex"])
X_test = pd.get_dummies(test_data,columns=["Sex"])

In [11]:
for df in [train_data, test_data]:
    # Sayısal sütunları medyan ile doldur (Age, Fare vb.)
    num_cols = df.select_dtypes(include=['number']).columns
    for col in num_cols:
        df[col] = df[col].fillna(df[col].median())

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [13]:
test_data

     PassengerId  Pclass     Sex   Age
0            892       3    male  34.5
1            893       3  female  47.0
2            894       2    male  62.0
3            895       3    male  27.0
4            896       3  female  22.0
..           ...     ...     ...   ...
413         1305       3    male  27.0
414         1306       1  female  39.0
415         1307       3    male  38.5
416         1308       3    male  27.0
417         1309       3    male  27.0

[418 rows x 4 columns]

In [14]:
y = train_data["Survived"]

features = [ "Sex"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!