<a href="https://colab.research.google.com/github/beyzadurdu6619/ML/blob/main/UnderFitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#UnderFitting -Az ÖĞRENME
#OverFitting -Aşırı ÖĞRENME
#BalangeFitting -Dengeli ÖĞRENME

In [7]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [5]:
df=sns.load_dataset("diamonds")

In [8]:
df.head(3)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [9]:
df=pd.get_dummies(df,columns=["cut","color","clarity"],drop_first=True)

In [10]:
df.head(3)

,carat,depth,table,price,x,y,z,cut_Premium,cut_Very Good,cut_Good,...,color_H,color_I,color_J,clarity_VVS1,clarity_VVS2,clarity_VS1,clarity_VS2,clarity_SI1,clarity_SI2,clarity_I1
0,0.23,61.5,55.0,326,3.95,3.98,2.43,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,0.21,59.8,61.0,326,3.89,3.84,2.31,True,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0.23,56.9,65.0,327,4.05,4.07,2.31,False,False,True,...,False,False,False,False,False,True,False,False,False,False

In [12]:
y=df["price"]
x=df.drop("price",axis=1)

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [20]:
l=LinearRegression()
model=l.fit(x_train,y_train)

In [21]:
model.score(x_test,y_test)

0.9189331350419387

In [22]:
model.score(x_train,y_train)

0.919994314909212

In [ ]:
#veri önişleme ve büyük veri seti verimlidir.
#train ve test scoreları arasındaki fark ne kadar azsa o kadatutarlıdır.